// TO DO

// - LISTED NEEDS TO BE "LAST UPDATED"                    -- DONE
// - STATUS BEING THE LAST UPDATED STATUS                 -- DONE
// - LISTED BEING LAST UPDATED DATE/TIME                  -- DONE

// - FAILED RUN NEEDS TO CHANGE STATUS TO PENDING         -- DONE

// - DEPENDENT DROP DOWN FOR FAILURE POINTS AND TYPES     -- DONE

// - WHEN FINAL QC IS PASS, STATUS IS SHELVED            -- DONE

// - LIST AND QC MODES IN THE MENU
// - MODE SWITCHING VIA MENU                          -- DONE
// - PREP INITIALIZES WITH PREPPED/ QC WITH SHELVED   -- DONE

// - HOVERABLE CELLS WITH PID HISTORY                   -- DONE
// FIX TO NOT INCLUDE CURRENT CELL HISTORY              -- DONE
// - DELETE NOTES WHEN DELETING A ROW                   -- DONE

// - FAILURE TYPE DETERMINES FINAL QC AND STATUS (ONLY SOME OF THEM)

// - SCANNER UI

// - GENERATE STATS VIA MENU - TODAY, YESTERDAY, THIS WEEK, THIS MONTH, ALL TIME
    // - HOW MANY FAILED, HOW MANY QC'D, HOW MANY PASSED
    // - HOW MANY FAILED, HOW MANY QC'D, HOW MANY PASSED

// - ADD SUB MENUES
    // - STATS
    // - ADMIN(?) DUPES/CAPS/NOTES
    // - MODES
