// TO DO

// - LISTED NEEDS TO BE "LAST UPDATED"                    -- DONE
// - STATUS BEING THE LAST UPDATED STATUS
// - LISTED BEING LAST UPDATED DATE/TIME

// - FAILED RUN NEEDS TO CHANGE STATUS TO PENDING         -- DONE

// - DEPENDENT DROP DOWN FOR FAILURE POINTS AND TYPES     -- DONE

// - SCANNER UI

// - DAILY STATS ABOVE EACH DAY ON THE BROWN BAR
// - HOW MANY FAILED, HOW MANY QC'D, HOW MANY PASSED
// - MAYBE GETS MOVED TO THE SCANNER UI


// - WHEN FINAL QC IS PASS, STATUS IS SHELVED            -- DONE

// - FAILURE TYPE DETERMINES FINAL QC AND STATUS (ONLY SOME OF THEM)

// - LIST AND QC MODES IN THE MENU
// - MODE SWITCHING VIA MENU                          -- DONE
// - PREP INITIALIZES WITH PREPPED/ QC WITH SHELVED   -- DONE

// - HOVERABLE CELLS WITH PID HISTORY
// FIX TO NOT INCLUDE CURRENT CELL HISTORY
// - DELETE NOTES WHEN DELETING A ROW                   -- DONE
